<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <LangVersion>default</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <AssemblyName>HanumanInstitute.LibMpv</AssemblyName>
    <RootNamespace>HanumanInstitute.LibMpv</RootNamespace>
    <Authors>Etienne Charland, Vadim Beloborodov, Jeff Baxter</Authors>
    <Description>MPV implementation for .NET including OpenGL, Native and Software renderers</Description>
    <Copyright>Copyright © 2023-2026 Etienne Charland</Copyright>
    <PackageProjectUrl>https://github.com/mysteryx93/LibMpv-OpenGL</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/mysteryx93/LibMpv-OpenGL</RepositoryUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>0.10.1</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <!-- <TargetFrameworks>net10.0;netstandard2.0;net10.0-android</TargetFrameworks> -->
    <TargetFrameworks>net10.0;netstandard2.0;net10.0-android</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <AndroidSupportedAbis>armeabi-v7a;arm64-v8a;x86_64</AndroidSupportedAbis>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <AndroidSupportedAbis>armeabi-v7a;arm64-v8a;x86_64</AndroidSupportedAbis>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ConfigureAwait.Fody" Version="3.4.0" PrivateAssets="All" />
    <PackageReference Include="HanumanInstitute.Validators" Version="2.1.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
